### ISSUE TITLE
Package rather large due to static library linking

### ISSUE THREAD

**Issue by wolfv** [conda-forge/bmad-feedstock#125]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

There are multiple large files in `bin/` that statically link to `libbmad.a`.

The package could be smaller if you would produce a `libbmad.dylib/.so` and link against that :)

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by hhslepicka** [comment]
@wolfv we are working with the package maintainers to check if the build system can be changed there to produce binaries linking to the shared libraries.

**Comment by wolfv** [comment]
Cool!

**Comment by DavidSagan** [comment]
This should be possible. The person who will be will be working on it says he will have time next week to look...

**Comment by DavidSagan** [comment]
Update: Some of the basic build scripts have been modified and are in testing. Light is seen at the end of the tunnel...

**Comment by hhslepicka** [comment]
**Update:**
- we changed to build only shared libraries (`.so` and `.dylib`) for this package.
- binaries were adjusted to link with shared libraries and reduce the overall size.

I am closing this issue but feel free to reopen it.
